spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.56/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug
